project:
  type: website
  output-dir: docs

website:
  title: "RTP R User Group"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contribute.qmd
      - posts.qmd # add your posts.qmd file to your navbar!
    right:
      - icon: github
        href: https://github.com/RTP-R-User-Group
        aria-label: GitHub
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

